### ISSUE TITLE
PDTB DATABASE

### ISSUE THREAD

**Issue by JuanPZuluaga** [tanfiona/CausalNewsCorpus#2]
Hello, 

We are participating in the challenge, and we would like to use the PDTB database (we have access to it). We were wondering if the scripts to prepare the data (as the one reported in the CNC paper) can be shared? Or at least the `train/dev/test/` split?

We used this Github repo for preparing the PDTB V3 database: https://github.com/najoungkim/pdtb3

Thanks.

**Comment by tanfiona** [comment]
Hi Juan, 

Could you send me an email at tan.f [at] u.nus.edu? I will share the scripts with you.

Thank you.
